package com.securecontacts.app.localization

import java.util.Locale

fun localized(value: String, vararg formatArgs: Any): String {
    val template = when (Locale.getDefault().language) {
        "en" -> englishText[value] ?: value
        "ru" -> value
        else -> value
    }
    return if (formatArgs.isEmpty()) template else String.format(Locale.getDefault(), template, *formatArgs)
}

private val englishText by lazy(LazyThreadSafetyMode.PUBLICATION) { mapOf(
    "Вход в приложение" to "Sign in",
    "Используйте отпечаток для входа" to "Use your fingerprint to sign in",
    "Изменить резервный пароль" to "Change backup password",
    "Изменить пароль помощи" to "Change help password",
    "Пароль должен содержать минимум 8 символов" to "Password must contain at least 8 characters",
    "Пароль помощи должен отличаться от резервного" to "Help password must differ from the backup password",
    "Экспорт завершён успешно" to "Export completed successfully",
    "Открытый экспорт завершён" to "Plain export completed",
    "Ошибка экспорта" to "Export failed",
    "Пароль изменён" to "Password changed",
    "Неверный текущий пароль" to "Incorrect current password",
    "Неверный резервный пароль" to "Incorrect backup password",
    "Экспорт с шифрованием" to "Encrypted export",
    "Введите резервный пароль для создания зашифрованной копии" to "Enter the backup password to create an encrypted copy",
    "Открытый экспорт" to "Plain export",
    "Введите резервный пароль. Файл будет сохранён без шифрования и будет содержать персональные данные, хэши паролей контактов и дополнительные поля." to "Enter the backup password. The file will be unencrypted and will contain personal data, contact password hashes, and custom fields.",
    "Импорт с шифрованием" to "Encrypted import",
    "Введите пароль для расшифровки файла" to "Enter the password to decrypt the file",
    "Открытый импорт" to "Plain import",
    "Введите текущий резервный пароль. Импорт разрешён только после проверки пароля, а файл не зашифрован." to "Enter the current backup password. Import is allowed only after verification, and the file is not encrypted.",
    "Разблокировка контакта" to "Unlock contact",
    "Используйте отпечаток пальца" to "Use your fingerprint",
    "Удалить контакт" to "Delete contact",
    "Удалить этот контакт без возможности восстановления?" to "Delete this contact permanently?",
    "Удалить" to "Delete",
    "Отмена" to "Cancel",
    "Контакты" to "Contacts",
    "Поиск" to "Search",
    "Добавить контакт" to "Add contact",
    "Поиск контактов..." to "Search contacts…",
    "Очистить" to "Clear",
    "Все" to "All",
    "Только активные" to "Active only",
    "Контакты не найдены" to "No contacts found",
    "Номер скопирован" to "Phone number copied",
    "Аватар" to "Avatar",
    "Копировать номер" to "Copy phone number",
    "Позвонить" to "Call",
    "Защищено" to "Protected",
    "Даты" to "Dates",
    "Нет предстоящих дат" to "No upcoming dates",
    "Неизвестный" to "Unknown",
    "День рождения" to "Birthday",
    "Сегодня!" to "Today!",
    "Завтра" to "Tomorrow",
    "Напоминания" to "Reminders",
    "Скрыть завершённые" to "Hide completed",
    "Показать завершённые" to "Show completed",
    "Нет напоминаний" to "No reminders",
    "Нет активных напоминаний" to "No active reminders",
    "Просрочено" to "Overdue",
    "Сегодня" to "Today",
    "Предстоящие" to "Upcoming",
    "Без даты" to "No date",
    "Завершено" to "Completed",
    "Все разговоры" to "All conversations",
    "Назад" to "Back",
    "Нет записей о разговорах" to "No conversation records",
    "Защищённые Контакты" to "Secure Contacts",
    "Введите пароль для входа" to "Enter password to sign in",
    "Войти" to "Sign in",
    "Использовать отпечаток" to "Use fingerprint",
    "Неверный пароль" to "Incorrect password",
    "Пароль" to "Password",
    "Редактировать" to "Edit",
    "Разблокировать" to "Unlock",
    "Поделиться" to "Share",
    "Поделиться контактом" to "Share contact",
    "Статус контакта" to "Contact status",
    "Активный (общаюсь)" to "Active (in touch)",
    "Неактивный (не общаюсь)" to "Inactive (not in touch)",
    "Телефон" to "Phone",
    "Эл. почта" to "Email",
    "Электронная почта" to "Email",
    "Адрес" to "Address",
    "Место работы" to "Workplace",
    "Должность" to "Position",
    "Источник" to "Source",
    "Чем может помочь" to "Can help with",
    "Дополнительная информация" to "Additional information",
    "Категория" to "Category",
    "Социальные сети" to "Social networks",
    "События" to "Events",
    "Повторяется" to "Repeats",
    "Дата" to "Date",
    "Отправить email" to "Send email",
    "Защищённое содержимое" to "Protected content",
    "Введите пароль или используйте биометрию для просмотра" to "Enter the password or use biometrics to view",
    "Новая запись о разговоре" to "New conversation entry",
    "О чём разговаривали" to "What did you discuss?",
    "Добавить запись" to "Add entry",
    "Сохранить" to "Save",
    "ОК" to "OK",
    "Новый контакт" to "New contact",
    "Редактировать контакт" to "Edit contact",
    "Основная информация" to "Basic information",
    "Имя *" to "Name *",
    "Источник (Как познакомились?)" to "Source (How did you meet?)",
    "Добавить фото" to "Add photo",
    "Безопасность" to "Security",
    "Изменить пароль" to "Change password",
    "Оставьте пустым, чтобы сохранить текущий пароль" to "Leave blank to keep the current password",
    "Новый пароль" to "New password",
    "Пароль *" to "Password *",
    "Подтвердите новый пароль" to "Confirm new password",
    "Подтвердите пароль *" to "Confirm password *",
    "Пароли не совпадают" to "Passwords do not match",
    "Показать или скрыть пароль" to "Show or hide password",
    "Новая" to "New",
    "Новый" to "New",
    "Нет" to "None",
    "Теги" to "Tags",
    "Добавить соцсеть" to "Add social network",
    "Добавить событие" to "Add event",
    "Добавить напоминание" to "Add reminder",
    "Пользовательские поля" to "Custom fields",
    "Добавить поле" to "Add field",
    "Добавить" to "Add",
    "Тип (напр., Telegram, WhatsApp)" to "Type (e.g. Telegram, WhatsApp)",
    "Имя пользователя" to "Username",
    "Ссылка (необязательно)" to "Link (optional)",
    "Название" to "Title",
    "Выберите дату" to "Choose a date",
    "Комментарий" to "Comment",
    "Повторяется ежегодно" to "Repeats yearly",
    "Установить дату" to "Set date",
    "Название поля" to "Field name",
    "Значение поля" to "Field value",
    "Помощь" to "Help",
    "Вкладка защищена паролем" to "This tab is password-protected",
    "Введите пароль для доступа" to "Enter password for access",
    "Введите пароль для доступа к вкладке 'Помощь'" to "Enter the password to access the Help tab",
    "Установить пароль" to "Set password",
    "Установите пароль длиной не менее 8 символов для защиты вкладки 'Помощь'" to "Set a password with at least 8 characters to protect the Help tab",
    "Подтвердите пароль" to "Confirm password",
    "Установить" to "Set",
    "Нет контактов с информацией о помощи" to "No contacts with help information",
    "Поиск по полю 'Чем может помочь'..." to "Search by the Can help with field…",
    "Чем может помочь:" to "Can help with:",
    "Советы по поиску" to "Search tips",
    "Поиск по имени, номеру телефона (последние 4 цифры), месту работы, должности или источнику" to "Search by name, phone number (last 4 digits), workplace, position, or source",
    "Недавние поиски" to "Recent searches",
    "Результаты не найдены" to "No results found",
    "Попробуйте другой поисковый запрос" to "Try a different search query",
    "Настройки" to "Settings",
    "Внешний вид" to "Appearance",
    "Тёмная тема (AMOLED)" to "Dark theme (AMOLED)",
    "Чёрный фон для OLED экранов" to "Black background for OLED displays",
    "Биометрическая разблокировка" to "Biometric unlock",
    "Использовать отпечаток для разблокировки" to "Use fingerprint to unlock",
    "Блокировка приложения" to "App lock",
    "Пароль при входе" to "Sign-in password",
    "Установить пароль для входа" to "Set a sign-in password",
    "Этот пароль будет запрашиваться при каждом запуске приложения" to "This password will be requested each time the app starts",
    "Убрать" to "Remove",
    "Включено" to "Enabled",
    "Выключено" to "Disabled",
    "Управление данными" to "Data management",
    "Экспорт" to "Export",
    "Защищённая резервная копия с паролем" to "Password-protected backup",
    "Импорт" to "Import",
    "Восстановление из зашифрованной копии" to "Restore from an encrypted backup",
    "JSON без шифрования, доступен после проверки резервного пароля" to "Unencrypted JSON available after backup-password verification",
    "Импорт JSON без шифрования после проверки резервного пароля" to "Import unencrypted JSON after backup-password verification",
    "Управление тегами" to "Manage tags",
    "Управление категориями" to "Manage categories",
    "История разговоров" to "Conversation history",
    "Все записи о разговорах с контактами" to "All conversation entries with contacts",
    "Версия %s" to "Version %s",
    "Резервный пароль" to "Backup password",
    "Пароль помощи" to "Help password",
    "Подтвердите резервный пароль" to "Confirm backup password",
    "Подтвердите пароль помощи" to "Confirm help password",
    "Добро пожаловать в Защищённые Контакты" to "Welcome to Secure Contacts",
    "Давайте настроим ваши пароли безопасности" to "Let’s set up your security passwords",
    "Минимум 8 символов. Пароль используется для зашифрованного экспорта/импорта и экстренного доступа к данным." to "At least 8 characters. This password is used for encrypted export/import and emergency data access.",
    "Минимум 8 символов. Это вторичный пароль для помощи, он должен отличаться от резервного." to "At least 8 characters. This secondary password protects Help and must differ from the backup password.",
    "Запомните эти пароли! Их нельзя восстановить при утере." to "Remember these passwords. They cannot be recovered if lost.",
    "Далее" to "Next",
    "Готово" to "Done",
    "Введите пароль для просмотра защищённой информации" to "Enter the password to view protected information",
    "Выбрано" to "Selected",
    "Тегов пока нет" to "No tags yet",
    "Категорий пока нет" to "No categories yet",
    "Создать первый тег" to "Create the first tag",
    "Создать первую категорию" to "Create the first category",
    "Добавить тег" to "Add tag",
    "Добавить категорию" to "Add category",
    "Редактировать тег" to "Edit tag",
    "Редактировать категорию" to "Edit category",
    "Название тега" to "Tag name",
    "Название категории" to "Category name",
    "Цвет" to "Color",
    "Создать" to "Create",
    "Ошибка: %s" to "Error: %s",
    "Импортировано: %d контактов" to "Imported: %d contacts",
    "Всего: %d | Активных: %d | Неактивных: %d" to "Total: %d | Active: %d | Inactive: %d",
    "ДР: %s" to "Birthday: %s",
    "%d дн." to "%d days",
    "1 нед." to "1 week",
    "%d нед." to "%d weeks",
    "1 мес." to "1 month",
    "%d мес." to "%d months",
    "(%d дн.)" to "(%d days)",
    "%d лет" to "%d years old",
    " (%d дн. назад)" to " (%d days ago)",
    " (через %d дн.)" to " (in %d days)",
    "%d результат" to "%d result",
    "%d результатов" to "%d results",
    "Телефон: %s" to "Phone: %s",
    "Работа: %s" to "Workplace: %s",
    "Должность: %s" to "Position: %s",
    "Источник: %s" to "Source: %s",
    "Введите пароль для просмотра защищённой информации %s" to "Enter the password to view %s’s protected information",
    "Введите пароль" to "Enter password",
    "Вторичный пароль для помощи" to "Secondary password for Help",
    "Изменить" to "Change",
    "Используется для зашифрованного экспорта/импорта" to "Used for encrypted export/import",
    "Оптимизировано для Android-устройств" to "Optimized for Android devices",
    "Подтвердить" to "Confirm",
    "Разблокировать контакт" to "Unlock contact",
    "Создать категорию" to "Create category",
    "Создать тег" to "Create tag",
    "Текущий пароль" to "Current password"
) }
